algoritmo "semnome"
// Função :
// Autor :
// Data : 08/01/2020
// Seção de Declarações 
var

nome: caractere
idade: inteiro

inicio
// Seção de Comandos

escreva("Digite seu nome: ")
leia(nome)

escreva("Digite sua idade: ")
leia(idade)

se(idade <=18)entao
  escreval(nome," vc nao pode tirar a cnh por menos de 18 anos")
senao
  escreva(nome," vc pode tirar a cnh por ter mais de 18 anos")
fimse
 
fimalgoritmo
